# Generated by Django 4.2.13 on 2024-06-25 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miliga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquiposCompetencias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('partidos_jugados', models.IntegerField(default=0)),
                ('partidos_ganados', models.IntegerField(default=0)),
                ('partidos_empatados', models.IntegerField(default=0)),
                ('partidos_perdidos', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_competencias', to='miliga.competencias')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_competencias', to='miliga.equipos')),
            ],
            options={
                'verbose_name': 'Equipos Competencias',
                'verbose_name_plural': 'Equipos Competencias',
                'db_table': 'equiposCompetencias',
            },
        ),
        migrations.DeleteModel(
            name='EquipoCompetencia',
        ),
    ]
