# Generated by Django 4.2.13 on 2024-06-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miliga', '0002_equiposcompetencias_delete_equipocompetencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competencias',
            options={'verbose_name': 'Competencia', 'verbose_name_plural': 'Competencias'},
        ),
        migrations.AddField(
            model_name='competencias',
            name='tipo',
            field=models.CharField(choices=[('Puntos', 'Puntos'), ('Eliminatoria', 'Eliminatoria')], default='Puntos', max_length=255),
        ),
        migrations.AlterModelTable(
            name='competencias',
            table='competencias',
        ),
    ]
