# Generated by Django 4.2.13 on 2024-06-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miliga', '0003_alter_competencias_options_competencias_tipo_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='equiposcompetencias',
            constraint=models.UniqueConstraint(fields=('equipo', 'competencia'), name='unique_equipo_competencia'),
        ),
    ]
