# Generated by Django 4.2.13 on 2024-06-11 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('avenida_calle', models.CharField(max_length=200)),
                ('localidad', models.CharField(max_length=100)),
                ('alcaldia_municipio', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=15)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='api.alumno')),
            ],
        ),
    ]
